### ISSUE TITLE
Skills xp not saving

### ISSUE THREAD

**Issue by NexusHK** [Auxilor/EcoSkills#63]
**Describe the bug**
Players' skill didnt save and relogging the server cause it to roll back.

**To Reproduce**
happened after the latest update, I did try using some older version of ecoskills but the issue still occurs.

**Expected behavior**
Data should be saved in real time and relogging wont cause the progress to roll back.

**Screenshots**
I have included a video below.

**Server Information (please complete the following information):**
- Version: 
Current: git-Purpur-1563 (MC: 1.18.1)*
Previous: git-Purpur-1541 (MC: 1.18.1)
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads

- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
eco 6.29.2
ecoskills 1.21.2

https://user-images.githubusercontent.com/101035548/159804569-2e1a293b-a93d-4492-960b-cb8f6a0d2890.mp4

**Comment by iSeitan** [comment]
Using the same server jar and EcoSkills version it sometimes happened to my player as well

**Comment by NexusHK** [comment]
> Using the same server jar and EcoSkills version it sometimes happened to my player as well

just tried with the latest 1.18.1 version of purpur, no luck still

Current: git-Purpur-1566 (MC: 1.18.1)*
Previous: git-Purpur-1563 (MC: 1.18.1)
* You are running the latest version

**Comment by Plxsi** [comment]
Oh wow this has been a bug for 5 days!

**Comment by WillFP** [comment]
any differences between eco 6.29.2 and 6.30.2? very important to know this because I don't know where the problem lies otherwise

**Comment by Plxsi** [comment]
I had the same problem on the previous version.

**Comment by WillFP** [comment]
Fixed in latest eco

**Comment by NexusHK** [comment]
using eco 6.31.1 and ecoskills 1.21.3
still not saving data correctly
